"""initial migration: add is_active to bus

Revision ID: 1e5ecb6be005
Revises: 
Create Date: 2026-03-17 11:20:09.710773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5ecb6be005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bookings_ticket_token'))

    with op.batch_alter_table('bus_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('speed',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('heading',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_bus_id'), type_='unique')
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('route_stops_route_id_stop_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('route_stops_route_id_stop_order_key'), type_='unique')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_stops_name'))
        batch_op.create_index('idx_stops_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trips_departure_time'))
        batch_op.drop_index(batch_op.f('idx_trips_route_id'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_trips_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_trips_departure_time'), ['departure_time'], unique=False)

    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index('idx_stops_geom', postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_stops_name'), ['name'], unique=False)
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))

    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('route_stops_route_id_stop_order_key'), ['route_id', 'stop_order'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('route_stops_route_id_stop_id_key'), ['route_id', 'stop_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))

    with op.batch_alter_table('bus_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('unique_bus_id'), ['bus_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('heading',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('captured_at')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bookings_ticket_token'), ['ticket_token'], unique=False)

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
